services:
  web:
    restart: always
    image: ghcr.io/informatyzacja/parliamentary-system/web:main
    ports:
      - 3000:3000
    depends_on:
      - api
    env_file:
      - .env
  api:
    restart: always
    image: ghcr.io/informatyzacja/parliamentary-system/api:main
    ports:
      - 1337:1337
    volumes:
      - ${STRAPI_PUBLIC_FOLDER}:/app/apps/api/public/
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    restart: always
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_FOLDER=${DATABASE_FOLDER}
    ports:
      - 5432:5432
    volumes:
      - $DATABASE_FOLDER:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
