services:
  frontend:
    restart: always
    build:
      context: ./frontend
    ports:
      - 80:3000
    volumes:
      - ./frontend/.env:/app/.env

  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - 81:1337
    volumes:
      - ./backend/public/:/app/public/
      - ./backend/.env:/app/.env
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
