version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=informatyzacja
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=parliamentarystrapi
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
