services:
  web:
    restart: always
    build:
      context: ./apps/
      dockerfile: ./web/Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./web/.env:/app/web/.env
    depends_on:
      - api

  api:
    restart: always
    build:
      context: ./apps/
      dockerfile: ./api/Dockerfile

    ports:
      - 81:1337
    volumes:
      - ./api/public/:/app/api/public/
      - ./api/.env:/app/api/.env
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_FOLDER=${DATABASE_FOLDER}
    ports:
      - 5432:5432
    volumes:
      - $DATABASE_FOLDER:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
