services:
  web:
    restart: no
    image: parliamentary-system-web
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - parliamentary-system
    env_file:
      - apps/web/.env
  api:
    restart: no
    image: parliamentary-system-api
    ports:
      - 1337:1337
    volumes:
      - ./apps/api/public/:/app/api/public/
    depends_on:
      - postgres
    networks:
      - parliamentary-system
    env_file:
      - apps/api/.env
  postgres:
    restart: no
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_FOLDER=${DATABASE_FOLDER}
    ports:
      - 5432:5432
    volumes:
      - $DATABASE_FOLDER:/var/lib/postgresql/data
    networks:
      - parliamentary-system

volumes:
  postgres:
    driver: local

networks:
  parliamentary-system:
    name: 'parliamentary-system'
