name: CD

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://parlament.samorzad.pwr.edu.pl
    steps:
      - name: Deploy to remote host
        uses: appleboy/ssh-action@v0.1.10
        env:
          CI: true
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.KEY }}
          envs: CI
          script: |
            cd ${{ secrets.APP_DIR }}
            rm .env
            touch .env
            echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
            echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env
            echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
            cd frontend
            rm .env.local
            touch .env.local
            echo NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }} >> .env.local
            echo NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} >> .env.local
            echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env.local
            echo USOS_CLIENT_ID=${{ secrets.USOS_CLIENT_ID }} >> .env.local
            echo USOS_CLIENT_SECRET=${{ secrets.USOS_CLIENT_SECRET }} >> .env.local
            echo USOS_BASE_URL=${{ secrets.USOS_BASE_URL }} >> .env.local
            echo NODE_ENV=production >> .env.local
            cd ..
            cd backend
            rm .env
            touch .env
            echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
            echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env
            echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
            echo USOS_CLIENT_ID=${{ secrets.USOS_CLIENT_ID }} >> .env
            echo USOS_CLIENT_SECRET=${{ secrets.USOS_CLIENT_SECRET }} >> .env
            echo USOS_BASE_URL=${{ secrets.USOS_BASE_URL }} >> .env
            cd ..
            git pull
            pnpm install --frozen-lockfile
            pnpm build
            pm2 reload ecosystem.config.js

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: Install pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ vars.GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GIT_COMMITTER_EMAIL }}
        run: pnpm semantic-release
