name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'auto-dependency-upgrade']

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Setup yarn
        run: yarn set version 3.6.1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup GitHub Actions cache for Turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
        with:
          cache-prefix: parliamentary_

      - name: Format check
        run: yarn format:check

      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build
        run: docker compose -f docker-compose.build.yml build
