name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'auto-dependency-upgrade']

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup yarn
        run: |
          yarn set version 3.6.1
      - name: Run install
        run: yarn install --immutable
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
        with:
          cache-prefix: parliamentary_
      - name: format
        run: yarn format:check
      - name: lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Setup yarn
        run: yarn set version 3.6.1
      - name: Setup env
        run: |
          cd apps/web
          touch .env.local
          echo NEXTAUTH_URL=http://localhost:3000 >> .env.local
          echo NEXT_PUBLIC_API_URL=http://0.0.0.0:1337 >> .env.local
          echo NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} >> .env.local
          echo USOS_CLIENT_ID=${{ secrets.USOS_CLIENT_ID }} >> .env.local
          echo USOS_CLIENT_SECRET=${{ secrets.USOS_CLIENT_SECRET }} >> .env.local
          echo USOS_BASE_URL=${{ secrets.USOS_BASE_URL }} >> .env.local
          echo NODE_ENV=production >> .env.local
          cd ../..
      - name: Run install
        run: yarn install --immutable
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
        with:
          cache-prefix: parliamentary_
      - name: Build
        run: yarn build
