name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'auto-dependency-upgrade']

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Setup yarn
        run: yarn set version 3.6.1

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup GitHub Actions cache for Turbo
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
        with:
          cache-prefix: parliamentary_

      - name: Format check
        run: yarn format:check

      - name: Lint
        run: yarn lint

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: informatyzacja/parliamentary-system-web:${{ github.sha }}
          cache-from: type=registry,ref=informatyzacja/parliamentary-system-web:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max

  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: informatyzacja/parliamentary-system-api:${{ github.sha }}
          cache-from: type=registry,ref=informatyzacja/parliamentary-system-api:buildcache
          cache-to: type=registry,ref=informatyzacja/parliamentary-system-api:buildcache,mode=max
